---
name: Download Artifact (https://github.com/nektos/act aware)
description: Download artifact using actions/download-artifact@v4 on act and actions/download-artifact@v8 on GitHub Actions.

runs:
  using: composite
  steps:
    - name: Upload artifact (act)
      if: ${{ env.ACT == 'true' }}
      # https://github.com/actions/download-artifact/releases/tag/v4.3.0
      uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
      with:
        path: .goreleaser/
        pattern: WinPin_*

    - name: Upload artifact (GitHub)
      if: ${{ env.ACT != 'true' }}
      # https://github.com/actions/download-artifact/releases/tag/v8.0.1
      uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
      with:
        digest-mismatch: error
        path: .goreleaser/
        # A glob pattern to the artifacts that should be downloaded.
        # Ignored if name is specified.
        # Optional.
        pattern: WinPin_*
        skip-decompress: false
