# ref. https://github.com/actions/create-release

---
name: goreleaser

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag (e.g., 0.0.1)'
        required: true
        type: string
  #; Not all tags are to be released, so we don't use 'push' trigger.
  # push:
  #   tags:
  #     - "v*"

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        arch: [arm64, x86_64]
    # ref. .github/workflows/lint.yml
    runs-on: macos-26
    steps:
      - name: Checkout target code of build
        # https://github.com/actions/checkout/commit/9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          ref: refs/tags/${{ inputs.tag }}
          fetch-depth: 0
      - name: build
        run: |
          make build-app ARCH=${{ matrix.arch }} APP_VERSION=${{ inputs.tag }}
      # https://github.com/actions/upload-artifact#inputs
      - name: Upload artifact
        uses: ./.github/actions/upload-artifact/
        with:
          name: WinPin_${{ matrix.arch }}
          path: .build/${{ matrix.arch }}/
          if-no-files-found: error
          retention-days: 1
          overwrite: true
          include-hidden-files: false

  goreleaser:
    needs: build
    runs-on: macos-26
    steps:
      - name: Checkout only for .goreleaser.yaml
        # https://github.com/actions/checkout/commit/9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          ref: refs/tags/${{ inputs.tag }}
          fetch-depth: 0
      - name: Set up Go
        # https://github.com/actions/setup-go/commit/924ae3a1cded613372ab5595356fb5720e22ba16
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version: "1.26"
          cache: true # cache is only effective for golang projects.
          # Path to dependency files for caching
          cache-dependency-path: ".github/workflows/dummy/go.mod"
      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@f06c13b6b1a9625abc9e6e439d9c05a8f2190e94 #v7.2.3
        with:
          install-only: true
      - name: "[DEBUG] Show GoReleaser version"
        run: goreleaser -v

      - name: Download releaser targets
        uses: ./.github/actions/download-artifact/
      - name: "[DEBUG] Display structure of downloaded files"
        run: find .goreleaser/ -type f

      - name: Run GoReleaser (Prepare *.zip and homebrew/Casks/win-pin.rb)
        id: goreleaser_release
        uses: goreleaser/goreleaser-action@f06c13b6b1a9625abc9e6e439d9c05a8f2190e94 #v7.2.3
        with:
          distribution: goreleaser
          version: "~> v2"
          args: release --clean --verbose
        env:
          # GITHUB_TOKEN is required. ref.: https://goreleaser.com/customization/ci/actions/#token-permissions
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOMEBREW_TAP_GITHUB_TOKEN: ${{ secrets.HOMEBREW_TAP_GITHUB_TOKEN }}
          #; GORERELEASER_CURRENT_TAG ref. https://goreleaser.com/resources/cookbooks/set-a-custom-git-tag/
          GORELEASER_CURRENT_TAG: ${{ inputs.tag }}
      - name: "[DEBUG] Show GoReleaser artifacts"
        run: echo '${{ steps.goreleaser_release.outputs.artifacts }}'
      - name: "[DEBUG] Display structure of dist files"
        run: find dist/ -type f

      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@1f8e202ffddf94def7f42f6fa3a482e821489f9c # 2026.07.10.1
        with:
          stable: true
          #; If HOMEBREW_GITHUB_API_TOKEN is omitted, it is said that rate limiting is applied. 60 req / hour (per IP address).
          # env:
          #   HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: "[DEBUG] Check Homebrew"
        run: |
          brew --version
          brew --prefix

      - name: "format and lint cask file"
        run: HOMEBREW_DEVELOPER=1 brew style --fix ./dist/homebrew/Casks/win-pin.rb

      - name: Checkout tap branch created by the release command of goreleaser 
        # https://github.com/actions/checkout/commit/3d3c42e5aac5ba805825da76410c181273ba90b1
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # 7.0.1
        with:
          repository: aki-s/homebrew-tap
          token: ${{ secrets.HOMEBREW_TAP_GITHUB_TOKEN }}
          # Assume this branch is created by goreleaser 'homebrew_casks.repository'. See .goreleaser.yaml
          ref: "win-pin-${{ inputs.tag }}"
          persist-credentials: false
          path: tap-repo
      # ref. As for user.email https://api.github.com/users/github-actions%5Bbot%5D
      - name: "push updated Casks/win-pin.rb"
        run: |
          mkdir -p tap-repo/Casks/
          cp ./dist/homebrew/Casks/win-pin.rb ./tap-repo/Casks/
          cd tap-repo
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if ! git diff --quiet; then
            git add Casks/win-pin.rb
            git commit -m "style: fix brew style for win-pin"
            git push https://x-access-token:${{ secrets.HOMEBREW_TAP_GITHUB_TOKEN }}@github.com/aki-s/homebrew-tap.git HEAD:win-pin-${{ inputs.tag }}
          fi
          git status

      - name: Create Pull Request via GitHub CLI
        run: |
          cd tap-repo
          gh pr create \
            --repo aki-s/homebrew-tap \
            --head "win-pin-${{ inputs.tag }}" \
            --base main \
            --title "Brew cask update for win-pin version ${{ inputs.tag }}" \
            --body "" \
            --draft
        env:
          GH_TOKEN: ${{ secrets.HOMEBREW_TAP_GITHUB_TOKEN }}

